# Generated by Django 5.2.5 on 2025-08-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/student_profile_pics/'),
        ),
    ]
